const ACTION_TYPES = {
   // 
    GET_CONTACTS_ACTION: 'GET_CONTACTS_ACTION',
    GET_CONTACTS_REQUEST: 'GET_CONTACTS_REQUEST',
    GET_CONTACTS_SUCCESS: 'GET_CONTACTS_SUCCESS',
    GET_CONTACTS_ERROR: 'GET_CONTACTS_ERROR',
    //
    POST_CONTACTS_ACTION: 'POST_CONTACTS_ACTION',
    POST_CONTACTS_REQUEST: 'POST_CONTACTS_REQUEST',
    POST_CONTACTS_SUCCESS: 'POST_CONTACTS_SUCCESS',
    POST_CONTACTS_ERROR: 'POST_CONTACTS_ERROR',
    //
    PUT_CONTACTS_ACTION: 'PUT_CONTACTS_ACTION',
    PUT_CONTACTS_REQUEST: 'PUT_CONTACTS_REQUEST',
    PUT_CONTACTS_SUCCESS: 'PUT_CONTACTS_SUCCESS',
    PUT_CONTACTS_ERROR: 'PUT_CONTACTS_ERROR',
    //
    DELETE_CONTACTS_ACTION: 'DELETE_CONTACTS_ACTION',
    DELETE_CONTACTS_REQUEST: 'DELETE_CONTACTS_REQUEST',
    DELETE_CONTACTS_SUCCESS: 'DELETE_CONTACTS_SUCCESS',
    DELETE_CONTACTS_ERROR: 'DELETE_CONTACTS_ERROR',

}
export default ACTION_TYPES